micronaut:
  application:
    name: fantiumApi
  io:
    watch:
      paths: src/main
      reload: true
  server:
    cors:
      enabled: true


  security:
    authentication:  bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
netty:
  default:
    allocator:
      max-order: 3

datasources:
  fantium:
    url: ${JDBC_URL:`jdbc:postgresql://localhost:5432/fantium`}
    username: ${JDBC_USER:fantium}
    password: ${JDBC_PASSWORD:fantium}
    driverClassName: org.postgresql.Driver
    dialect: POSTGRES

jpa:
  default:
    entity-scan:
      packages:
        - com.fantium.domains
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true

kafka:
    bootstrap:
        servers: ${KAFKA_HOST:`localhost:9092`}

